### ISSUE TITLE
Передача паролей через MD5 больше не поддерживается

### ISSUE THREAD

**Issue by Finesse** [jhaoda/smscenter#5]
Создал аккаунт, попытался отправить СМС, указав MD5 пароля в качестве пароля (как в readme), получил ошибку №2 (неверный логин или пароль). В техподдержке сказали, что MD5 больше не поддерживается:

> Сегодня, 20:08:52 Служба поддержки:
> Сейчас хеш пароля не используется, пароль нужно передавать в чистом виде

 Упоминания MD5 в [документации](https://smsc.ru/api/) тоже нет.

**Comment by jhaoda** [comment]
Вообще-то они врут. Судя по всему, это только для для новых аккаунтов:
> Все указанные изменения в сервисе по обработке паролей не требуют обязательных действий со стороны клиентов, все программы и доступы в личные кабинеты продолжают работать

http://smsc.ru/news/73/novyi+sposob+hraneniya+i+upravleniya+parolyami/

Есть предложения?

**Comment by Finesse** [comment]
@jhaoda Судя по [преждней версии документации](http://web.archive.org/web/20171123043015/http://smsc.ru/api/), раньше можно было отправлять пароль в явном виде, так что, если в документации убрать упоминание MD5, то библиотека будет работать как со старыми аккаунтами, так и с новыми.

**Comment by jhaoda** [comment]
Исправлено в 93dcea7.
