### ISSUE TITLE
How to run the service? 

### ISSUE THREAD

**Issue by sheshankkodam** [jhaoda/smscenter#6]

**Comment by jhaoda** [comment]
@sheshankkodam what service?

**Comment by sheshankkodam** [comment]
> @sheshankkodam what service?

I would like `SMSC` and test it. Does this repo offer SMSC service or is it build for testing?

**Comment by jhaoda** [comment]
@sheshankkodam this repo is a wrapper for [smsc.ru](https://smsc.ru/) API.
